name: Bake AMI

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags' 

jobs:
  hcp-packer:
    runs-on: ubuntu-latest
    name: Run Packer
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "latest"

      - name: Run `packer init`
        id: init
        run: "packer init ./aws-amazonlinux-custom.pkr.hcl"

      - name: Run `packer validate`
        id: validate
        run: "packer validate ./aws-amazonlinux-custom.pkr.hcl"

      - name: Build Artifact
        run: packer build --var 'version=0.000.5' --var 'vpc_id=${{env.VPC_ID}}' --var 'subnet_id=${{env.SUBNET_ID}}' -color=false -on-error=abort ./aws-amazonlinux-custom.pkr.hcl
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
